### PR TITLE
Fix AT failures

### LINKED ISSUE #70: Fix stability of end to end tests
The end to end tests are failing due to peer failures in many of the PEEPs end to end tests.

### PR DESCRIPTION
**Pull request by jframe**
Improve stability of PEEPS end to end tests

* Wait for first block in QBFT tests before doing transactions to ensure that all nodes are creating blocks and not syncing rounds
* Use static nodes files instead of boot nodes to improve issues with peers not being found

Fixes #70

### CODE REVIEW

File: dsl/src/main/java/tech/pegasys/peeps/node/StaticNodesFile.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+    final List<String> enodeAddresses =
+        web3Providers.stream().map(Web3Provider::enodeAddress).collect(Collectors.toList());
+    enodeAddresses.remove(web3Provider.enodeAddress());
+    try {
+      objectMapper.writeValue(staticNodesFile.toFile(), enodeAddresses);
+      LOG.info(
+          "Creating static nodes file\n\tLocation: {} \n\tContents: {}",
+          staticNodesFile,
+          enodeAddresses);
+    } catch (IOException e) {
```
Comment (usmansaleem) [inline dsl/src/main/java/tech/pegasys/peeps/node/StaticNodesFile.java:59]: nit: final

File: dsl/src/main/java/tech/pegasys/peeps/node/StaticNodesFile.java [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+  }
+
+  public Path getStaticNodesFile() {
+    return staticNodesFile;
+  }
+
+  private void write(final Web3Provider web3Provider, final List<Web3Provider> web3Providers) {
+    final List<String> enodeAddresses =
+        web3Providers.stream().map(Web3Provider::enodeAddress).collect(Collectors.toList());
+    enodeAddresses.remove(web3Provider.enodeAddress());
```
Comment (usmansaleem) [inline dsl/src/main/java/tech/pegasys/peeps/node/StaticNodesFile.java:52]: nit: could use filter:
`web3Providers.stream().map(Web3Provider::enodeAddress).filter(enode -> !enode.equals(web3Provider.enodeAddress)).collect(Collectors.toList())`

**Review by usmansaleem — APPROVED** [review]
LGTM - minor comments.

File: dsl/src/main/java/tech/pegasys/peeps/node/StaticNodesFile.java (hunk 2 above)
Comment (jframe) [reply dsl/src/main/java/tech/pegasys/peeps/node/StaticNodesFile.java]: done

File: dsl/src/main/java/tech/pegasys/peeps/node/StaticNodesFile.java (hunk 1 above)
Comment (jframe) [reply dsl/src/main/java/tech/pegasys/peeps/node/StaticNodesFile.java]: done
